application/__init__.py
from flask import Flask
from .views import views
from config import Config


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    app.register_blueprint(views)
    return app

application/views.py
# Import needed modules
from functools import wraps

import hashlib
import requests
from flask import Blueprint, request, redirect, session, render_template, url_for, flash, jsonify

from config import Config
from .database import Database

# Initialize some global variables
apiKey = Config.API_KEY
baseApiUrl = f'http://newsapi.org/v2/top-headlines?country=ng&apiKey={apiKey}'
categoryApiUrl = f'http://newsapi.org/v2/top-headlines?country=ng&apiKey={apiKey}&category='
searchApiUrl = f'https://newsapi.org/v2/everything?apiKey={apiKey}&q='

# Create the views blueprint to handle all our views
views = Blueprint('views', __name__, template_folder='templates', static_folder='static')

# Initialize our database to be used for CRUD operations within the application
db = Database()


# UTILITY FUNCTIONS
def hash_password(password):
    """
    Takes a password and returns a hashed value to be stored in the database
    :param password: string
    :return: string
    """
    hashed = hashlib.sha256(password.encode('utf-8'))
    return hashed.hexdigest()


def login_required(f):
    """
    Decorator to ensure only logged in users have access to certain pages
    :param f: View
    :return: Function
    """

    @wraps(f)
    def wrap(*args, **kwargs):
        if 'name' in session:
            return f(*args, **kwargs)
        else:
            flash('You must be logged in to view this page', category='warning')
            return redirect(url_for('views.login'))

    return wrap


# Views

@views.route('/', methods=["GET", "POST"])
@views.route('/home/', methods=['GET', 'POST'])
def home():
    """
    Renders the homepage whenever the user enters '/' or '/home/' in the url
    Fetches latest news from the news api and sends it to the template
    :return: Template
    """
    categories = ['Technology', 'Sports', 'Health', 'Science', 'Entertainment', 'Business']
    if request.method == 'POST':
        q = request.form.get('q')
        try:
            response = requests.get(searchApiUrl + q)
            newslist = response.json()['articles']
        except requests.exceptions.ConnectionError:
            flash(f'An error occurred while fetching the news on {q}', category='danger')
            return render_template('search.html', newslist=None, q=q)
        else:
            return render_template('search.html', newslist=newslist, q=q)
    try:
        response = requests.get(baseApiUrl)
        newslist = response.json()['articles']
    except:
        flash('An error occurred while fetching the latest news', category='danger')
        return render_template('home.html', news=None, categories=categories)
    else:
        return render_template('home.html', newslist=newslist, categories=categories)


@views.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Renders the login page when the url path points to '/login/'
    Handles authenticating users and logging them in
    Sets the session name object if it does not exist
    :return: Template
    """
    if request.method == 'POST':
        name = request.form.get('username')
        password = request.form.get('password')
        if db.check_user(name, hash_password(password)):
            session['name'] = name
            flash('You have been logged in successfully', 'success')
            return redirect(url_for('views.home'))
        flash('Invalid username or password', category='danger')
    elif session.get('name') is not None:
        flash('You have already been logged in!', category='info')
        return redirect(url_for('views.home'))
    return render_template('login.html')


@views.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Renders the registration page for new users to sign up
    Hashes the password to be stored in the database for security
    Redirects to the home page on successful sign up
    Logs new users in automatically
    :return: Template
    """
    if request.method == 'POST':
        name = request.form.get('username')
        password = request.form.get('password')
        user_added = db.add_user(name, hash_password(
            password))  # Adds the user  to the database and checks if successfully added
        if user_added:
            session['name'] = name
            flash('Registration Successful', category='success')
            return redirect(url_for('views.home'))
        flash('User already exists', category='danger')
    return render_template('register.html')


@views.route('/logout/')
@login_required
def logout():
    """
    Logs the user out by removing the username from the session dict
    :return: Redirect
    """
    if session.get('name'):
        session.pop('name', None)
        flash('You have been logged out successfully', category='success')
        return redirect(url_for('views.home'))


@views.route('/category/<category>/')
@login_required
def category(category):
    """
    Fetches the news based on the requested category
    Displays the category page when the user requests
    :param category: string
    :return: Template
    """
    categories = ['Technology', 'Sports', 'Health', 'Science', 'Entertainment', 'Business']
    if category in categories:
        try:
            response = requests.get(categoryApiUrl + category)
            newslist = response.json()['articles']
            newslist = [{'title': news['title'], 'urlToImage': news['urlToImage'], 'description': news['description'],
                         'publishedAt': news['publishedAt'], 'author': news['author']} for news in newslist]
        except:
            flash('An error occurred while fetching the latest news', category='danger')
            return render_template('category.html', newslist=None, category=category)
        else:
            return render_template('category.html', newslist=newslist, category=category)
    flash('Category does not exist', 'danger')
    return redirect(url_for('views.home'))


@views.route('/api/setHistory/', methods={'POST'})
def setHistory():
    if request.method == 'POST':
        print(request.form.keys())
        return jsonify({'message': 'received'})

application/templates/category.html
{% extends 'index.html'%}
{% block content %}

   <div class="jumbotron text-center">
       <h3>All news relating to {{category}}</h3>
   </div>
<div class="p-1 m-1">
    <div class="container">
        <div class="row justify-content-center">
            {% if newslist %}
    {% for news in newslist %}
            <div class="col-md-4">
    <div class="card mb-4">
        <img src="{{news.urlToImage}}" alt="" class="card-img-top">
        <div class="card-body">
            <p class="lead">{{news.title}}</p>
            {% if news.description != None%}
            <p class="text-truncate">{{news.description}}</p>
            {% endif %}

            <div class="d-flex flex-column justify-content-between align-items-left pb-2">
                {% if news.author != None%}
                <p class="font-italic">- {{news.author}}</p>
                {% endif%}
                <small class="text-muted">{{news.publishedAt}}</small>
              </div>
            <button onclick="setHistory({{news}})" class="btn btn-dark">View</button>
        </div>
    </div></div>
    {%endfor%}
            {% else %}
            <a href="{{url_for('views.home')}}" class="btn btn-dark mt-5">Refresh</a>
            {% endif %}
            </div>
        </div>
</div>
    <script src="{{url_for('static', filename='newsfeed.js')}}"></script>
{% endblock %}

application/templates/home.html
{% extends 'index.html'%}
{% block content %}
   <div class="jumbotron text-center">
       <h3>A platform for news on all categories</h3>
       <p>Search for news on any topic of your choice</p>
       <form action="" method="post">
       <input type="text" name="q"><br>
       <button type="submit" class="btn btn-dark mt-3">Search</button>
           </form>
   </div>
<div class="p-1 m-1">
    <div class="container">
        <h4>All categories</h4>
        <div class="row justify-content-center">
            {% for category in categories %}
            <a href="{{url_for('views.category', category=category)}}" class="btn btn-dark m-1">{{category}}</a>
            {% endfor %}
        </div>
        <h4>Trending News</h4>
        <div class="row justify-content-center">
            {% if newslist %}
    {% for news in newslist %}
            <div class="col-md-4">
    <div class="card mb-4">
        <img src="{{news.urlToImage}}" alt="" class="card-img-top">
        <div class="card-body">
            <p class="lead">{{news.title}}</p>
            {% if news.description != None%}
            <p class="text-truncate">{{news.description}}</p>
            {% endif %}

            <div class="d-flex flex-column justify-content-between align-items-left pb-2">
                {% if news.author != None%}
                <p class="font-italic">- {{news.author}}</p>
                {% endif%}
                <small class="text-muted">{{news.publishedAt}}</small>
              </div>
            <a href="{{news.url}}" class="btn btn-dark">View</a>
        </div>
    </div></div>
    {%endfor%}
            {% else %}
            <a href="{{url_for('views.home')}}" class="btn btn-dark mt-5">Refresh</a>
            {% endif %}
            </div>
        </div>
</div>
{% endblock %}

application/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no">
    <title>{% block title %} News Feed {% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.css')}}">
    <script src="{{url_for('static', filename='jquery.min.js.download')}}"></script>
    <script src="{{url_for('static', filename='bootstrap.js')}}"></script>


</head>
{% block style %}
<style>
    .jumbotron{
    border-radius: 0;
    }
</style>
{% endblock %}
<body>
    <nav class="navbar navbar-dark bg-dark navbar-expand-md">
        <span class="navbar-brand">News Feed</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">

            <ul class="navbar-nav ml-auto">
                {% if session.get('name') != None%}
            <li class="nav-item"><span class="text-white nav-link">Welcome, {{session.get('name')}}</span></li>
            {% else %}
            <li class="nav-item"><span class="text-white nav-link">Welcome, Guest</span></li>
            {% endif %}
                <li class="nav-item"><a href="{{ url_for('views.home')}}" class="nav-link">Home</a></li>
                {% if session.get('name') != None%}
                <li class="nav-item"><a href="{{ url_for('views.logout')}}" class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{{ url_for('views.login')}}" class="nav-link">Login</a></li>
                {% endif %}
                <li class="nav-item"><a href="{{ url_for('views.register')}}" class="nav-link">Register</a></li>

            </ul>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="alert-{{category}}"><p class="p-2 mb-0">{{message}}</p></div>
        {% endfor %}
    {% endif %}
{% endwith %}
    {% block content %}
    {% endblock %}
</body>
</html>

application/templates/login.html
{% extends 'index.html' %}
{% block style %}
<style>
html,
body {
  height: 100%;
}


.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
  text-align: center;
}

.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
    <form class="form-signin" method="post" action="">
  <h1 class="h3 mb-3 font-weight-normal">Please Sign In</h1>
  <label for="inputUsername" class="sr-only">Username</label>
  <input type="text" id="inputUsername" class="form-control" placeholder="Username" required autofocus name="username">
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
  <button class="btn btn-dark" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2021-2022</p>
</form>
        </div>
    </div>
{% endblock %}

application/templates/register.html
{% extends 'index.html' %}
{% block style %}
<style>
html,
body {
  height: 100%;
}


.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: auto;
  text-align: center;
}

.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
    <form class="form-signin" method="post" action="">
  <h1 class="h3 mb-3 font-weight-normal">Please Sign Up</h1>
  <label for="inputUsername" class="sr-only">Username</label>
  <input type="text" id="inputUsername" class="form-control" placeholder="Username" required autofocus name="username">
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
  <button class="btn btn-dark" type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2021-2022</p>
</form>
        </div>
    </div>
{% endblock %}

application/templates/search.html
{% extends 'index.html'%}
{% block content %}
   <div class="jumbotron text-center">
       <h3>All news related to {{q}}</h3>
   </div>
<div class="p-1 m-1">
    <div class="container">
        <div class="row justify-content-center">
            {% if newslist %}
    {% for news in newslist %}
            <div class="col-md-4">
    <div class="card mb-4">
        <img src="{{news.urlToImage}}" alt="" class="card-img-top">
        <div class="card-body">
            <p class="lead">{{news.title}}</p>
            {% if news.description != None%}
            <p class="text-truncate">{{news.description}}</p>
            {% endif %}

            <div class="d-flex flex-column justify-content-between align-items-left pb-2">
                {% if news.author != None%}
                <p class="font-italic">- {{news.author}}</p>
                {% endif%}
                <small class="text-muted">{{news.publishedAt}}</small>
              </div>
            <a href="{{news.url}}" class="btn btn-dark">View</a>
        </div>
    </div></div>
    {%endfor%}
            {% else %}
            <a href="{{url_for('views.home')}}" class="btn btn-dark mt-5">Refresh</a>
            {% endif %}
            </div>
        </div>
</div>
{% endblock %}